/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vinayabhishek' at '10/12/17 7:45 PM' with Gradle 3.2.1
 *
 * @author vinayabhishek, @date 10/12/17 7:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
